# Generated by Django 2.2.12 on 2020-04-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20200419_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='value',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='expense',
            name='body',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
